name: msdspy11
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - annotated-types==0.6.0
      - anyio==4.2.0
      - blinker==1.7.0
      - certifi==2023.11.17
      - click==8.1.7
      - distro==1.9.0
      - flask==3.0.0
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - idna==3.6
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - lxml==4.9.4
      - markupsafe==2.1.3
      - openai==1.6.1
      - pillow==10.1.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - python-docx==1.1.0
      - python-dotenv==1.0.0
      - sniffio==1.3.0
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - werkzeug==3.0.1
