OPENAI_KEY: "********"
OPENAI_ENDPOINT: "https://apsl-ai.openai.azure.com/"
OPENAI_API_VERSION: "2023-05-15"
OPENAI_SEED: 123
MSDS_SHEETS_PATH: "./data/MSDS_sheets"
MSDS_DOC_HEADING: "MSDS SUMMARY SHEET"
MODEL_NAME: "Tech-transfer-GPT-4"
MODEL_TEMP: 0.001

MAP_DICT:
  0: "Basic Information"
  1: "Physical Properties"
  2: "Hazard related information"
  3: "Personal protection"
  4: "Handling information"
  5: "Solubility"
  6: "Any other relevant information"
  7: "First aid measures"
  8: "Flash point, degree C"
  9: "Fire-fighting measures"
  10: "IMDG code"
  11: "CAS Number"
  12: "UN number"
  13: "Transport hazard"